---
- name: Install package
  package:
    name: "{{ nginx_package }}"
    state: present

- name: Create available sites
  copy:
    content: "{{ item.value }}"
    dest: "{{ nginx_available_sites_dir }}/{{ item.key }}"
  loop: "{{ nginx_available_sites | dict2items }}"
  loop_control:
    label: "{{ item.key }}"

- name: Find all enabled sites
  find:
    path: "{{ nginx_enabled_sites_dir }}"
    file_type: link
  register: nginx_find_all_sites_enabled

- name: Set all enabled sites
  set_fact:
    nginx_all_sites_enabled: >
      {{ nginx_find_all_sites_enabled.files |
         map(attribute='path') |
         map('basename') |
         list }}

- name: Enable sites
  file:
    path: "{{ nginx_enabled_sites_dir }}/{{ item }}"
    src: "{{ nginx_available_sites_dir }}/{{ item }}"
    state: link
  loop: "{{ nginx_enabled_sites }}"

- name: Disable all other sites
  file:
    path: "{{ nginx_enabled_sites_dir }}/{{ item }}"
    state: absent
  loop: "{{ nginx_all_sites_enabled | difference(nginx_enabled_sites) }}"

- name: Start nginx
  service:
    name: "{{ nginx_service }}"
    enabled: yes
    state: started
