---
- name: Install package
  package:
    name: "{{ nginx_package }}"
    state: present

- name: Create config files
  copy:
    content: "{{ item.value }}"
    dest: "{{ nginx_config_dir }}/{{ item.key }}"
  loop: "{{ nginx_config_files | dict2items }}"
  loop_control:
    label: "{{ item.key }}"
  notify: Reload nginx

- name: Find all config files
  find:
    path: "{{ nginx_config_dir }}"
  register: nginx_find_all_config_files

- name: Set all deleted config files
  set_fact:
    nginx_deleted_config_files: >
      {{ nginx_find_all_config_files.files |
        map(attribute='path') |
        map('basename') |
        difference(nginx_config_files.keys()) |
        list }}

- name: Delete config files
  file:
    path: "{{ nginx_config_dir }}/{{ item }}"
    state: absent
  loop: "{{ nginx_deleted_config_files }}"
  notify: Reload nginx

- name: Create available sites
  copy:
    content: "{{ item.value }}"
    dest: "{{ nginx_available_sites_dir }}/{{ item.key }}"
  loop: "{{ nginx_available_sites | dict2items }}"
  loop_control:
    label: "{{ item.key }}"
  notify: Reload nginx

- name: Enable sites
  file:
    path: "{{ nginx_enabled_sites_dir }}/{{ item }}"
    src: "{{ nginx_available_sites_dir }}/{{ item }}"
    state: link
  loop: "{{ nginx_enabled_sites }}"
  notify: Reload nginx

- name: Find all enabled sites
  find:
    path: "{{ nginx_enabled_sites_dir }}"
    file_type: link
  register: nginx_find_all_enabled_sites

- name: Set disabled sites
  set_fact:
    nginx_disabled_sites: >
      {{ nginx_find_all_enabled_sites.files |
         map(attribute='path') |
         map('basename') |
         difference(nginx_enabled_sites) |
         list }}

- name: Disable sites
  file:
    path: "{{ nginx_enabled_sites_dir }}/{{ item }}"
    state: absent
  loop: "{{ nginx_disabled_sites }}"
  notify: Reload nginx

- name: Validate configuratation
  command: nginx -t
  changed_when: no

- name: Start nginx
  service:
    name: "{{ nginx_service }}"
    enabled: yes
    state: started
